robot1_arm:
  kinematics_solver: ur_kinematics/UR10KinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  arm_prefix: robot1_
robot2_arm:
  kinematics_solver: ur_kinematics/UR10KinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  arm_prefix: robot2_