# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: robot1_arm
  joint_model_group_pose: robot1_home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - robot1_shoulder_pan_joint
    - robot1_shoulder_lift_joint
    - robot1_elbow_joint
    - robot1_wrist_1_joint
    - robot1_wrist_2_joint
    - robot1_wrist_3_joint
    - robot1_left_finger_joint
    - robot1_right_finger_joint
    - robot2_shoulder_pan_joint
    - robot2_shoulder_lift_joint
    - robot2_elbow_joint
    - robot2_wrist_1_joint
    - robot2_wrist_2_joint
    - robot2_wrist_3_joint
    - robot2_left_finger_joint
    - robot2_right_finger_joint
  sim_control_mode: 1  # 0: position, 1: velocity
controller_list:
  - name: robot1_arm_trajectory_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - robot1_shoulder_pan_joint
      - robot1_shoulder_lift_joint
      - robot1_elbow_joint
      - robot1_wrist_1_joint
      - robot1_wrist_2_joint
      - robot1_wrist_3_joint

  - name: robot1_left_finger_action_controller
    action_ns: gripper_cmd
    default: True
    type: GripperCommand
    joints:
      - robot1_left_finger_joint

  - name: robot1_right_finger_action_controller
    action_ns: gripper_cmd
    default: True
    type: GripperCommand
    joints:
      - robot1_right_finger_joint

  - name: robot2_arm_trajectory_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - robot2_shoulder_pan_joint
      - robot2_shoulder_lift_joint
      - robot2_elbow_joint
      - robot2_wrist_1_joint
      - robot2_wrist_2_joint
      - robot2_wrist_3_joint
  
  - name: robot2_left_finger_action_controller
    action_ns: gripper_cmd
    default: True
    type: GripperCommand
    joints:
      - robot2_left_finger_joint
  
  - name: robot2_right_finger_action_controller
    action_ns: gripper_cmd
    default: True
    type: GripperCommand
    joints:
      - robot2_right_finger_joint