# TODO: determine all these parameters
num_samples: 1000
grasp_quality_thresh: 0.7
max_antipodal_normal_angle: 0.1
max_antipodal_position_angle: 0.1
max_equator_normal_angle: 0.1
gripper_pad_distance: 0.1
gripper_pad_length: 0.3
output_path: $(find chair_manipulation_grasp_detection_advanced)/cfg/grasp_database.yaml
chair_models:
  - mesh: $(find chair_manipulation_chair_models)/models/dining_chair/meshes/dining_chair.ply
    point_cloud: $(find chair_manipulation_chair_models)/models/dining_chair/point_clouds/dining_chair.pcd